### ISSUE TITLE
Receiving this error

### ISSUE THREAD

**Issue by shagtimetim** [gberg927/MMM-DisneyWaitTimes#15]
When attempting to clone I receive this error.  I have no idea what this means.  Certified NOOB here

Cloning into 'MMM-DisneyWaitTimes'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by gberg927** [comment]
You are most likely receiving this issue because you do not have your SSH public key linked to your GitHub profile. If you are new to Git/Github I'd suggest using HTTPS to get the repo locally.

Try doing 
`git clone https://github.com/gberg927/MMM-DisneyWaitTimes.git`

This will prompt you to enter your Github username and password.

Let me know how that goes.

**Comment by shagtimetim** [comment]
@gberg927   Thank you, this did resolve the issue
